name: CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Give executable permissions to list_requirement.sh
        run: chmod +x app/list_requirement.sh

      - name: Run list_requirement.sh
        run: ./app/list_requirement.sh

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/credit_scoring:latest

      - name: Run unit tests
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/credit_scoring:latest python -m unittest discover

      - name: SSH into EC2 Instance and Update Docker Image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull your-dockerhub-username/your-repo-name:your-tag
            docker stop running-container-name
            docker rm running-container-name
            docker run -d --name new-container-name -p 80:80 your-dockerhub-username/your-repo-name:your-tag
